# Remove unnecessary files after hexo generate.
minify: true

# è‡ªå®šä¹‰æ–‡ä»¶
custom_file_path:
  head: source/_data/head.njk
  style: source/_data/styles.styl
  footer: source/_data/footer.njk

# ä¸»é¢˜
scheme: Gemini

# æš—é»‘æ¨¡å¼
darkmode: true

# åˆ›ä½œè€…åè®®
creative_commons:
    sidebar: true
    post: false

# ä¸»èœå•
menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  lab:
    default: /lab/ || fa fa-flask fa-fw
    file: https://home.lyz05.cn:5244/ || fa fa-folder
    note: /note/ || fa fa-clipboard
    uptime: https://stats.uptimerobot.com/XnEypsn5VN || fas fa-heartbeat
    FC: /FC/ || fas fa-rocket
    HomeAssistant: https://home.lyz05.cn:8123/ || fa fa-robot
  books: /books/ || fa fa-book
  movie: /movies/ || fa fa-film
  about: /about/ || fa fa-user
  links: /links/ || fas fa-link

menu_settings:
# å¾½æ ‡
  badges: true

# å¤´åƒ
avatar:
  url: /images/avatar.webp
  rounded: true

# ç¤¾äº¤é“¾æ¥
social:
  GitHub: https://github.com/lyz05 || fab fa-github
  E-Mail: mailto:blog@lyz05.cn || fa fa-envelope
  çŸ¥ä¹: http://www.zhihu.com/people/liu-yuan-zhe-16 || iconfont icon-douban
  è±†ç“£: http://www.douban.com/people/140286755/ || iconfont icon-zhihu

# ç¤¾äº¤å›¾æ ‡
social_icons:
  icons_only: true

footer:
  since: 2015

# Postå…ƒä¿¡æ¯æ˜¾ç¤º
post_meta:
  created_at: true
  updated_at:
    enable: false


mobile_layout_economy: true

back2top:
  scrollpercent: true

math:
  mathjax:
    enable: true

# cloudflare_analytics: ebddc42d1db14fe2b0307d0dce464211

local_search:
  enable: true
  preload: true

pdf:
  enable: true

# ä»£ç å—
codeblock:
  copy_button:
    enable: true
  fold:
    enable: true
    height: 500

# åŠ¨ç”»
motion:
  enable: false
  async: true
  transition:
    post_block: fadeIn
    post_header:
    post_body:
    coll_header:
    sidebar: fadeInUp

# é¡¶éƒ¨è¿›åº¦æ¡
pace:
  enable: true

# å›¾ç‰‡æ‡’åŠ è½½
lazyload: true

# ä¸­è‹±æ–‡æ–‡å­—ç•™ç™½
pangu: true

# é¡µé¢é¢„åŠ è½½
quicklink:
  enable: true
  home: true
  archive: true

# Postå…³è”githubç¼–è¾‘åšæ–‡
post_edit:
  enable: true
  url: https://github.com/lyz05/lyz05.github.io/tree/blog/source/ # Link for view source

# ä¸ºå­—ä½“æ’ä»¶å»ºç«‹æ—©æœŸé“¾æ¥
preconnect: true

tag_icon: true


github_banner:
  enable: true
  permalink: https://github.com/lyz05

# SEO
index_with_subtitle: true

vendors:
  # The CDN provider of NexT internal scripts.
  # Available values: local | jsdelivr | unpkg | cdnjs
  # Warning: If you are using the latest master branch of NexT, please set `internal: local`
  internal: jsdelivr
  # The default CDN provider of third-party plugins.
  # Available values: local | jsdelivr | unpkg | cdnjs
  # Dependencies for `plugins: local`: https://github.com/next-theme/plugins
  plugins: jsdelivr


# Leancloudç»Ÿè®¡å­—æ•°ä¸è¯„è®ºåŠŸèƒ½
valine:
  enable: true
  appId: IOO0v6UWzOQE94hPLrgXiQhg-9Nh9j0Va
  appKey: vBfyrsgGJnqg8qG3PD4MglR8
  visitor: true
  serverURLs: https://ioo0v6uw.lc-cn-n1-shared.com
  recordIP: true

# Mermaid æ ‡ç­¾
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme:
    light: default
    dark: dark

# æ‰“èµè®¾ç½®
reward_settings:
  enable: true
  animation: false
  comment: èµä¸ªé¸¡è…¿ğŸ—

reward:
  wechatpay: /images/wechatpay.png
  alipay: /images/alipay.jpg
  #paypal: /images/paypal.png
  #bitcoin: /images/bitcoin.png
